iLDimParam = KAPI.ksLDimParam(iKompasObject.GetParamStruct(LDefin2D.ko_LDimParam))

iDimDrawingParam = KAPI.ksDimDrawingParam(iLDimParam.GetDPar())
iDimDrawingParam.Init()
iDimDrawingParam.ang = 0.0
iDimDrawingParam.lenght = 0.0
iDimDrawingParam.pl1 = False
iDimDrawingParam.pl2 = False
iDimDrawingParam.pt1 = 1
iDimDrawingParam.pt2 = 1
iDimDrawingParam.shelfDir = 0
iDimDrawingParam.textBase = 0
iDimDrawingParam.textPos = 0

iLDimSourceParam = KAPI.ksLDimSourceParam(iLDimParam.GetSPar())
iLDimSourceParam.Init()
iLDimSourceParam.basePoint = 1
iLDimSourceParam.dx = 0.0
iLDimSourceParam.dy = 8
iLDimSourceParam.ps = 0
iLDimSourceParam.x1 = 0.0
iLDimSourceParam.y1 = 0.0
iLDimSourceParam.x2 = 0.0 
iLDimSourceParam.y2 = 0.0

iDimTextParam = KAPI.ksDimTextParam(iLDimParam.GetTPar())
iDimTextParam.Init(0)
iDimTextParam.bitFlag = 0
iDimTextParam.sign = 0
iDimTextParam.stringFlag = False
iDimTextParam.style = 3

iCharArray = KAPI.ksDynamicArray(iDimTextParam.GetTextArr())
iChar255 = KAPI.ksChar255(iKompasObject.GetParamStruct(LDefin2D.ko_Char255))
iChar255.Init()
iChar255.str = "1.0"
iCharArray.ksAddArrayItem(-1, iChar255)

iDocument2D.ksLinDimension(iLDimParam)

